name: Draft Release Note

on:
  workflow_dispatch:
    inputs:
      release:
        required: true
        type: choice
        description: 'A username passed from the caller workflow'
        options:
        - major
        - minor
        - patch

jobs:
  draft-release-note:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_IT_VERSION: 14.2.1
    steps:
      - uses: actions/checkout@v2

      - name: Set releaser settings
        run: |
          git config --global user.name release-machine
          git config --global user.email email@example.com

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Package Install
        run: npm i -g release-it

      - name: Patch release
        id: minor
        run: release-it -- ${{ github.event.inputs.release }} --ci
